package autoimage;

import ij.Prefs;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Karsten
 */
public class LayoutPlateManagerDlg extends javax.swing.JDialog {

    private PlateConfiguration startUpConfig;
    private static String lastFileLocation="";

    public LayoutPlateManagerDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (lastFileLocation.equals(""))
            lastFileLocation=Prefs.getHomeDir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        plateWidthField = new javax.swing.JFormattedTextField();
        plateHeightField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        fileLocationLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        leftEdgeToA1Field = new javax.swing.JFormattedTextField();
        topEdgeToA1Field = new javax.swing.JFormattedTextField();
        wellDiameterField = new javax.swing.JFormattedTextField();
        wellDistanceField = new javax.swing.JFormattedTextField();
        wellDepthField = new javax.swing.JFormattedTextField();
        bottomThicknessField = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        wellShapeComboBox = new javax.swing.JComboBox();
        platenameField = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        materialComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        plateLengthField = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        columnsSpinner = new javax.swing.JSpinner();
        rowsSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Plate Layout Manager");
        setMinimumSize(new java.awt.Dimension(454, 486));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel1.setText("Plate width (mm):");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel2.setText("Plate height (mm):");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel3.setText("Well shape:");

        plateWidthField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        plateWidthField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        plateHeightField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        plateHeightField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel4.setText("Dist. left edge - center A1 (mm):");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel5.setText("Dist. top edge - center A1 (mm):");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel6.setText("Well diameter (mm):");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel7.setText("Well depth (mm):");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel8.setText("Plate bottom thickness (mm):");

        closeButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel9.setText("Plate name:");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel10.setText("Location:");

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoimage/resources/openDoc.png"))); // NOI18N
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoimage/resources/saveDoc.png"))); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        newButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        fileLocationLabel.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        fileLocationLabel.setText("jLabel11");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel11.setText("Well columns:");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel12.setText("Well rows:");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel13.setText("Well-to-well distance (mm):");

        leftEdgeToA1Field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        leftEdgeToA1Field.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        topEdgeToA1Field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        topEdgeToA1Field.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        wellDiameterField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        wellDiameterField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        wellDistanceField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        wellDistanceField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        wellDepthField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        wellDepthField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        bottomThicknessField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        bottomThicknessField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        wellShapeComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        wellShapeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Round", "Square" }));

        platenameField.setText("jFormattedTextField11");
        platenameField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel14.setText("Plate bottom material:");

        materialComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        materialComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Glass", "Plastic", "Other" }));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel15.setText("Plate length (mm):");

        plateLengthField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.000"))));
        plateLengthField.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N

        columnsSpinner.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        columnsSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 48, 1));

        rowsSpinner.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        rowsSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 32, 1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(jLabel6)
                            .add(jLabel5)
                            .add(jLabel7)
                            .add(jLabel13)
                            .add(jLabel8)
                            .add(jLabel14))
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(leftEdgeToA1Field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .add(topEdgeToA1Field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .add(wellDiameterField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .add(wellDistanceField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .add(wellDepthField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .add(bottomThicknessField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .add(closeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(materialComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jLabel10)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(fileLocationLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(platenameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(newButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(openButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(saveButton))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel15)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2))
                                .add(6, 6, 6)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(plateLengthField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(jLabel12))
                                    .add(layout.createSequentialGroup()
                                        .add(plateWidthField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(0, 0, Short.MAX_VALUE))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(0, 0, Short.MAX_VALUE)
                                        .add(jLabel11))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(plateHeightField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(jLabel3)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, columnsSpinner)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, rowsSpinner)
                                    .add(wellShapeComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .add(12, 12, 12))))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1)
                    .add(jSeparator2))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {bottomThicknessField, leftEdgeToA1Field, topEdgeToA1Field, wellDepthField, wellDiameterField, wellDistanceField}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel9)
                    .add(newButton)
                    .add(openButton)
                    .add(saveButton)
                    .add(platenameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(fileLocationLabel))
                .add(6, 6, 6)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(13, 13, 13)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(plateWidthField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11)
                    .add(columnsSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(jLabel15)
                    .add(plateLengthField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rowsSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(plateHeightField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(wellShapeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .add(1, 1, 1)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(leftEdgeToA1Field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(topEdgeToA1Field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(wellDiameterField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(wellDistanceField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(wellDepthField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(bottomThicknessField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(materialComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(21, 21, 21)
                .add(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setConfiguration(PlateConfiguration configuration) {
        if (configuration!=null) {
            platenameField.setValue(configuration.name);
            if (configuration.fileLocation.equals("")) {
                configuration.fileLocation=lastFileLocation;
            }
            fileLocationLabel.setText(configuration.fileLocation);
            plateWidthField.setValue(configuration.width/1000);
            plateLengthField.setValue(configuration.length/1000);
            plateHeightField.setValue(configuration.height/1000);
            columnsSpinner.setValue(configuration.columns);
            rowsSpinner.setValue(configuration.rows);
            leftEdgeToA1Field.setValue(configuration.distLeftEdgeToA1/1000);
            topEdgeToA1Field.setValue(configuration.distTopEdgeToA1/1000);
            wellDiameterField.setValue(configuration.wellDiameter/1000);
            wellDistanceField.setValue(configuration.wellDistance/1000);
            wellDepthField.setValue(configuration.wellDepth/1000);
            wellShapeComboBox.setSelectedItem(configuration.wellShape);
            materialComboBox.setSelectedItem(configuration.bottomMaterial);
            bottomThicknessField.setValue(configuration.bottomThickness/1000);
        }
        lastFileLocation=configuration.fileLocation;
        startUpConfig=configuration;
    }
    
    private PlateConfiguration getConfiguration() {
        PlateConfiguration configuration=new PlateConfiguration();
        configuration.name=(String)platenameField.getValue();
        configuration.fileLocation=fileLocationLabel.getText();
        configuration.width=1000*((Number)plateWidthField.getValue()).doubleValue();
        configuration.length=1000*((Number)plateLengthField.getValue()).doubleValue();
        configuration.height=1000*((Number)plateHeightField.getValue()).doubleValue();
        configuration.columns=((Number)columnsSpinner.getValue()).intValue();
        configuration.rows=((Number)rowsSpinner.getValue()).intValue();
        configuration.distLeftEdgeToA1=1000*((Number)leftEdgeToA1Field.getValue()).doubleValue();
        configuration.distTopEdgeToA1=1000*((Number)topEdgeToA1Field.getValue()).doubleValue();
        configuration.wellDiameter=1000*((Number)wellDiameterField.getValue()).doubleValue();
        configuration.wellDistance=1000*((Number)wellDistanceField.getValue()).doubleValue();
        configuration.wellDepth=1000*((Number)wellDepthField.getValue()).doubleValue();
        configuration.wellShape=(String)wellShapeComboBox.getSelectedItem();
        configuration.bottomMaterial=(String)materialComboBox.getSelectedItem();
        configuration.bottomThickness=1000*((Number)bottomThicknessField.getValue()).doubleValue();
        return configuration;
    }

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        //check if modified and if yes, open save dialog
        if (!startUpConfig.equals(getConfiguration())) {
            int result=JOptionPane.showConfirmDialog(this, "Save current plate configuration?", "Plate Layout Manager", JOptionPane.YES_NO_CANCEL_OPTION);
            switch (result) {
                case JOptionPane.CANCEL_OPTION: {
                    break;
                }
                case JOptionPane.NO_OPTION: {
                    dispose();
                    break;
                }
                case JOptionPane.YES_OPTION: {
                    saveLayout();
                    break;
                }
            }
        } else {
            dispose();
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveLayout() {
        PlateConfiguration config = getConfiguration();
        if ((config.width < config.distLeftEdgeToA1+(config.columns-1)*config.wellDistance+config.wellDiameter)
                || (config.length < config.distTopEdgeToA1+(config.rows-1)*config.wellDistance+config.wellDiameter)) {
            JOptionPane.showMessageDialog(this,"Cannot fit all wells into layout.");
            return;
        }
        if (config.wellDiameter <= 0) {
            JOptionPane.showMessageDialog(this,"Well diameter has to be larger than 0");
            return;
        }
        if (config.wellDistance < config.wellDiameter) {
            JOptionPane.showMessageDialog(this,"Well-to-well distance has to be larger than the well diameter.");
            return;
        }
        AcqLayout acqLayout= new AcqPlateLayout(new File(config.fileLocation,config.name),config);
        JFileChooser jfc = new JFileChooser();
        if ("".equals(config.fileLocation)) {
            config.fileLocation=Prefs.getHomeDir();
        }
        jfc.setCurrentDirectory(new File(config.fileLocation));
        jfc.setSelectedFile(new File(config.name));
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfc.setMultiSelectionEnabled(false);
        jfc.ensureFileIsVisible(acqLayout.getFile());
        if (jfc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            if (!Utils.getExtension(f).toLowerCase().equals(".txt")) {
                JOptionPane.showMessageDialog(this,"Not a txt file");
                f = new File(f.getAbsolutePath() + ".txt");
            }
            if (f.exists()) {
                int overwrite = JOptionPane.showConfirmDialog(null, "Replace " + f.getName(), "", JOptionPane.YES_NO_OPTION);
                if (overwrite != JOptionPane.YES_OPTION) {
                    return;
                }
            }
            acqLayout.setName(f.getName());
            acqLayout.setFile(f);

            FileWriter fw;
            try {
                fw = new FileWriter(f);
                JSONObject layoutObj=new JSONObject();
                try {
                    JSONObject obj=acqLayout.toJSONObject();
                    if (obj!=null) {
                        layoutObj.put(AcqLayout.TAG_LAYOUT,obj);
                        fw.write(layoutObj.toString(4));
                    }
                    startUpConfig=config;
                } catch (JSONException ex) {
                    JOptionPane.showMessageDialog(null,"Error parsing Acquisition Layout as JSONObject.");
                    Logger.getLogger(AcqLayout.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null,"Error saving Acquisition Layout as JSONObject.");
                    Logger.getLogger(AcqLayout.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    fw.close();
                }        
            } catch (IOException ex) {
                Logger.getLogger(AcqLayout.class.getName()).log(Level.SEVERE, null, ex);
            }
            platenameField.setText(acqLayout.getName());
            lastFileLocation=acqLayout.getFile().getParent();
            fileLocationLabel.setText(lastFileLocation);
            acqLayout.setModified(false);
        }       
    }
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saveLayout();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        //check if modified and if yes, open save dialog
        if (!startUpConfig.equals(getConfiguration())) {
            int result=JOptionPane.showConfirmDialog(this, "Save current plate configuration?", "Plate Layout Manager", JOptionPane.YES_NO_CANCEL_OPTION);
            switch (result) {
                case JOptionPane.CANCEL_OPTION: {
                    return;
                }
                case JOptionPane.NO_OPTION: {
                    break;
                }
                case JOptionPane.YES_OPTION: {
                    saveLayout();
                    break;
                }
            }
        }
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(fileLocationLabel.getText()));
        int returnVal = fc.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            if (!Utils.getExtension(f).toLowerCase().equals(".txt")) {
                JOptionPane.showMessageDialog(null, "Layout files have to be in txt format.\nLayout has not been loaded.", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            AcqLayout layout=AcqLayout.loadLayout(fc.getSelectedFile());
            if (layout==null) {
                JOptionPane.showMessageDialog(this, "Layout file '"+f.getName()+"' could not be found or read!");
                return;
            }
            if (!(layout instanceof AcqPlateLayout)) {
                JOptionPane.showMessageDialog(this, "Layout file '"+f.getName()+"' could not be found or read!");
                return;
            }
            PlateConfiguration configuration=new PlateConfiguration();
            configuration.name=layout.getName();
            configuration.fileLocation=layout.getFile().getParent();
            configuration.width=layout.getWidth();
            configuration.length=layout.getLength();
            configuration.height=layout.getHeight();
            configuration.columns=((AcqPlateLayout)layout).getColumns();
            configuration.rows=((AcqPlateLayout)layout).getRows();
            configuration.distLeftEdgeToA1=((AcqPlateLayout)layout).getLeftEdgeToA1();
            configuration.distTopEdgeToA1=((AcqPlateLayout)layout).getTopEdgeToA1();
            configuration.wellDiameter=((AcqPlateLayout)layout).getWellDiameter();
            configuration.wellDistance=((AcqPlateLayout)layout).getWellDistance();
            configuration.wellDepth=((AcqPlateLayout)layout).getWellDepth();
            configuration.wellShape=((AcqPlateLayout)layout).getWellShape();
            configuration.bottomMaterial=layout.getBottomMaterial();
            configuration.bottomThickness=layout.getBottomThickness();
            setConfiguration(configuration);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_openButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        //check if modified and if yes, open save dialog
        if (!startUpConfig.equals(getConfiguration())) {
            int result=JOptionPane.showConfirmDialog(this, "Save current plate configuration?", "Plate Layout Manager", JOptionPane.YES_NO_CANCEL_OPTION);
            switch (result) {
                case JOptionPane.CANCEL_OPTION: {
                    return;
                }
                case JOptionPane.NO_OPTION: {
                    break;
                }
                case JOptionPane.YES_OPTION: {
                    saveLayout();
                    break;
                }
            }
        }
        PlateConfiguration config=new PlateConfiguration();
 //       if (lastFileLocation.equals("")) {
 //           lastFileLocation=Prefs.getHomeDir();
 //       }
        config.fileLocation=lastFileLocation;
        setConfiguration(config);
    }//GEN-LAST:event_newButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField bottomThicknessField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton closeButton;
    private javax.swing.JSpinner columnsSpinner;
    private javax.swing.JLabel fileLocationLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JFormattedTextField leftEdgeToA1Field;
    private javax.swing.JComboBox materialComboBox;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    private javax.swing.JFormattedTextField plateHeightField;
    private javax.swing.JFormattedTextField plateLengthField;
    private javax.swing.JFormattedTextField plateWidthField;
    private javax.swing.JFormattedTextField platenameField;
    private javax.swing.JSpinner rowsSpinner;
    private javax.swing.JButton saveButton;
    private javax.swing.JFormattedTextField topEdgeToA1Field;
    private javax.swing.JFormattedTextField wellDepthField;
    private javax.swing.JFormattedTextField wellDiameterField;
    private javax.swing.JFormattedTextField wellDistanceField;
    private javax.swing.JComboBox wellShapeComboBox;
    // End of variables declaration//GEN-END:variables
}
