package autoimage;

import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;

/**
 *
 * @author Karsten Siller
 */
public class TimeChooserDlg extends javax.swing.JDialog {

    private final Calendar cachedDelta;

    public TimeChooserDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        okButton.setActionCommand("Ok");
        cancelButton.setActionCommand("Cancel");
        cachedDelta=Calendar.getInstance(TimeZone.getTimeZone("UTC"));
        //initialize with 0s delay
        cachedDelta.setTimeInMillis(0);
    }

    public void addOkCancelListener(ActionListener al) {
        okButton.addActionListener(al);
        cancelButton.addActionListener(al);
    }
    
    public void setStartTime(AcqSetting.ScheduledTime time) {
        Calendar absTime=Calendar.getInstance();
        switch (time.type) {
            case AcqSetting.ScheduledTime.ASAP: {
                asapButton.setSelected(true);
                break;
            }
            case AcqSetting.ScheduledTime.DELAY: {
                //precaution: trim to h/min/s
                cachedDelta.setTimeInMillis(time.startTimeMS % (1000 * 3600 * 24));
                deltaHSpinner.setValue(cachedDelta.get(Calendar.HOUR));
                deltaMinSpinner.setValue(cachedDelta.get(Calendar.MINUTE));
                deltaSecSpinner.setValue(cachedDelta.get(Calendar.SECOND));
                deltaButton.setSelected(true);
                break;
            }
            case AcqSetting.ScheduledTime.ABSOLUTE: {
                absTime.setTimeInMillis(time.startTimeMS);
                absoluteButton.setSelected(true);
                break;
            }
        }
        absTimeSpinner.setValue(absTime.getTime());
    }
    
    public AcqSetting.ScheduledTime getStartTime() {
        AcqSetting.ScheduledTime startTime=new AcqSetting.ScheduledTime(0,0);
        if (asapButton.isSelected()) {
            startTime.type=AcqSetting.ScheduledTime.ASAP;
            startTime.startTimeMS=0;
        } else if (deltaButton.isSelected()) {
            startTime.type=AcqSetting.ScheduledTime.DELAY;
            startTime.startTimeMS=cachedDelta.getTimeInMillis();
        } else if (absoluteButton.isSelected()) {
            startTime.type=AcqSetting.ScheduledTime.ABSOLUTE;
            Date d=(Date)absTimeSpinner.getValue();
            startTime.startTimeMS=d.getTime();
        }
        return startTime;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        asapButton = new javax.swing.JRadioButton();
        deltaButton = new javax.swing.JRadioButton();
        absoluteButton = new javax.swing.JRadioButton();
        deltaHSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deltaMinSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        deltaSecSpinner = new javax.swing.JSpinner();
        absTimeSpinner = new javax.swing.JSpinner();
        nowButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(asapButton);
        asapButton.setText("As soon as possible");
        asapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asapButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(deltaButton);
        deltaButton.setText("Delay after start of previous sequence");
        deltaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deltaButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(absoluteButton);
        absoluteButton.setText("At specific time");
        absoluteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absoluteButtonActionPerformed(evt);
            }
        });

        deltaHSpinner.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        deltaHSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        deltaHSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deltaHSpinnerStateChanged(evt);
            }
        });

        jLabel1.setText("h");

        jLabel2.setText("min");

        deltaMinSpinner.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        deltaMinSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        deltaMinSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deltaMinSpinnerStateChanged(evt);
            }
        });

        jLabel3.setText("s");

        deltaSecSpinner.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        deltaSecSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        deltaSecSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deltaSecSpinnerStateChanged(evt);
            }
        });

        absTimeSpinner.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        absTimeSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1424723174548L), null, null, java.util.Calendar.MINUTE));

        nowButton.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        nowButton.setText("Now");
        nowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(asapButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(deltaButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(deltaHSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(deltaMinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(deltaSecSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(absoluteButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(absTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(nowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(asapButton)
                .addGap(12, 12, 12)
                .addComponent(deltaButton)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deltaHSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deltaMinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deltaSecSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(12, 12, 12)
                .addComponent(absoluteButton)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(absTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nowButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton)
                    .addComponent(cancelButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void asapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asapButtonActionPerformed
        deltaHSpinner.setEnabled(false);
        deltaMinSpinner.setEnabled(false);
        deltaSecSpinner.setEnabled(false);
        absTimeSpinner.setEnabled(false);
        nowButton.setEnabled(false);
    }//GEN-LAST:event_asapButtonActionPerformed

    private void deltaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deltaButtonActionPerformed
        deltaHSpinner.setEnabled(true);
        deltaMinSpinner.setEnabled(true);
        deltaSecSpinner.setEnabled(true);
        absTimeSpinner.setEnabled(false);
        nowButton.setEnabled(false);
    }//GEN-LAST:event_deltaButtonActionPerformed

    private void absoluteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absoluteButtonActionPerformed
        deltaHSpinner.setEnabled(false);
        deltaMinSpinner.setEnabled(false);
        deltaSecSpinner.setEnabled(false);
        absTimeSpinner.setEnabled(true);
        nowButton.setEnabled(true);
    }//GEN-LAST:event_absoluteButtonActionPerformed

    private void deltaHSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deltaHSpinnerStateChanged
        cachedDelta.set(Calendar.HOUR, (Integer)deltaHSpinner.getValue());
    }//GEN-LAST:event_deltaHSpinnerStateChanged

    private void deltaMinSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deltaMinSpinnerStateChanged
        cachedDelta.set(Calendar.MINUTE, (Integer)deltaMinSpinner.getValue());
    }//GEN-LAST:event_deltaMinSpinnerStateChanged

    private void deltaSecSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deltaSecSpinnerStateChanged
        cachedDelta.set(Calendar.SECOND, (Integer)deltaSecSpinner.getValue());
    }//GEN-LAST:event_deltaSecSpinnerStateChanged

    private void nowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nowButtonActionPerformed
        Calendar now=Calendar.getInstance();
        absTimeSpinner.setValue(now.getTime());
    }//GEN-LAST:event_nowButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner absTimeSpinner;
    private javax.swing.JRadioButton absoluteButton;
    private javax.swing.JRadioButton asapButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton deltaButton;
    private javax.swing.JSpinner deltaHSpinner;
    private javax.swing.JSpinner deltaMinSpinner;
    private javax.swing.JSpinner deltaSecSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton nowButton;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
